Exception:
ValueError: Intentional failure for testing.

Logging:
CRITICAL	custom_logger	Called 'before_node_run' with args: (Node(name=logger_hook_custom_logger:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)]),)
INFO	ordeq.io	Loading Literal('name')
INFO	ordeq.runner	Running node Node(name=logger_hook_custom_logger:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)])
CRITICAL	custom_logger	Called 'after_node_run' with args: (Node(name=logger_hook_custom_logger:hello, inputs=[Literal('name')], outputs=[IO(idx=ID1)]),)
CRITICAL	custom_logger	Called 'before_node_run' with args: (Node(name=logger_hook_custom_logger:fail),)
INFO	ordeq.runner	Running node Node(name=logger_hook_custom_logger:fail)
CRITICAL	custom_logger	Called 'on_node_call_error' with args: (Node(name=logger_hook_custom_logger:fail), ValueError('Intentional failure for testing.'))